### ISSUE TITLE
Manage Keys fails if etcd db is too large.

### ISSUE THREAD

**Issue by rhheisterberg** [gtamas/etcdmanager#60]
Getting the following error when I switch to the Manage Keys page when the etcd db gets too large:

Could not perform operation. Error: Error: 8 RESOURCE_EXHAUSTED: Received message larger than max (12320704 vs. 4194304)

Is there a way to fix/avoid this?

Thanks

**Comment by gtamas** [comment]
@rheisterberg 
Thanks for the info, we'll look into it. Probably the fix will be release in 1.2.1.

**Comment by ssadok** [comment]
Hi,
Any upgrades please ?

Thanks

**Comment by gtamas** [comment]
yeah this is because of how reading of keys is implemented right now. It does not support pagination. I will fix this issue as soon as I can.

I'm closing this because I track this one under:

https://github.com/gtamas/etcdmanager/issues/78

Please check the above link for updates. The fix will be part of next release.
